export const Users = [
  {
    id: 1,
    profilePicture: "assets/persons/img1.jpg",
    username: "Akin Shot",
  },
  {
    id: 2,
    profilePicture: "assets/persons/img2.jpg",
    username: "Shittu Kabirat",
  },
  {
    id: 3,
    profilePicture: "assets/persons/img3.jpg",
    username: "Akere Atinuke",
  },
  {
    id: 4,
    profilePicture: "assets/persons/img4.jpg",
    username: "Later Khalid ",
  },
  {
    id: 5,
    profilePicture: "assets/persons/img5.png",
    username: "Akere Sulaimon",
  },
  {
    id: 6,
    profilePicture: "assets/persons/img6.jpg",
    username: "Alademomi Micheal",
  },
  {
    id: 7,
    profilePicture: "assets/persons/img7.jpg",
    username: "Balogun Kofoworola",
  },
  {
    id: 8,
    profilePicture: "assets/persons/img8.jpg",
    username: "Lawal Fano",
  },
  {
    id: 9,
    profilePicture: "assets/persons/img9.png",
    username: "Lawal Fano",
  },
  {
    id: 10,
    profilePicture: "assets/persons/img10.jpg",
    username: "Lawal Fano",
  },
];
// console.log(Users.filter((user) => user.id === 2)[0]);

export const Posts = [
  {
    id: 1,
    decs: "Love For All, Hatred For None",
    photo: "assets/post/p1.jpg",
    date: "5 min ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "When life serves you lemons, mae lemonades",
    photo: "assets/post/p2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 30,
    comment: 75,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/p3.jpg",
    date: "8 days ago",
    userId: 3,
    like: 42,
    comment: 50,
  },
  {
    id: 4,
    photo: "assets/post/p4.jpg",
    date: "5 hrs ago",
    userId: 4,
    like: 34,
    comment: 16,
  },
  {
    id: 5,
    desc: "The more responsible you become, the easier your life becomes... nodeSkin",
    photo: "assets/post/p5.jpg",
    date: "20 mins ago",
    userId: 5,
    like: 45,
    comment: 19,
  },
  {
    id: 6,
    desc: "Always let the Wolf inside you reflect through your sheep clothing.. nodeSkin",
    photo: "assets/post/p6.jpg",
    date: "10 mins ago",
    userId: 6,
    like: 58,
    comment: 32,
  },
  {
    id: 7,
    desc: "You never born, you dey form daarrdy.. nodeSkin",
    photo: "assets/post/p7.jpg",
    date: "10 mins ago",
    userId: 6,
    like: 102,
    comment: 62,
  },

  {
    id: 8,
    desc: "Only if shadows could fly and don't just get buried on the surfaces, in which they attract like an offset chameleon.. nodeSkin",
    photo: "assets/post/p8.png",
    date: "10 mins ago",
    userId: 8,
    like: 12,
    comment: 2,
  },
  {
    id: 9,
    desc: "Always let the Wolf inside you reflect through your sheep clothing.. nodeSkin",
    photo: "assets/post/p9.jpg",
    date: "10 mins ago",
    userId: 9,
    like: 85,
    comment: 68,
  },
  {
    id: 10,
    desc: "Order amongst chaos... nodeSkin",
    photo: "assets/post/p10.png",
    date: "10 mins ago",
    userId: 10,
    like: 172,
    comment: 42,
  }
];
